<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\QuanLyNhaTro\Views\PhongTros\NewFolder\**" />
    <Content Remove="Areas\QuanLyNhaTro\Views\PhongTros\NewFolder\**" />
    <EmbeddedResource Remove="Areas\QuanLyNhaTro\Views\PhongTros\NewFolder\**" />
    <None Remove="Areas\QuanLyNhaTro\Views\PhongTros\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
	<!-- Thư viện kết nối PostgreSQL -->
	<PackageReference Include="ClosedXML" Version="0.104.2" />
	<PackageReference Include="MailKit" Version="4.17.0" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />

	<!-- Các thư viện hỗ trợ EF Core & Migration -->
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.4">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Ajax" Version="3.2.6" />
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="4.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\QuanLyNhaTro\Middlewares\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
