// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyChoThuePhongTroWeb.Data;

#nullable disable

namespace QuanLyChoThuePhongTroWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260802095846_UpdateHoaDonDichVuModels")]
    partial class UpdateHoaDonDichVuModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Areas.QuanLyNhaTro.Models.DichVuChiNhanh", b =>
                {
                    b.Property<int>("DichVuChiNhanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DichVuChiNhanhId"));

                    b.Property<int>("ChiNhanhId")
                        .HasColumnType("integer");

                    b.Property<int>("DichVuId")
                        .HasColumnType("integer");

                    b.Property<double>("GiaDichVu")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DichVuChiNhanhId");

                    b.HasIndex("DichVuId");

                    b.HasIndex("ChiNhanhId", "DichVuId")
                        .IsUnique();

                    b.ToTable("dich_vu_chi_nhanh");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.ChiNhanh", b =>
                {
                    b.Property<int>("ChiNhanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChiNhanhId"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaChiNhanh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChiNhanhId");

                    b.HasIndex("MaChiNhanh")
                        .IsUnique();

                    b.ToTable("chi_nhanh");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ChiTietHoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChiTietHoaDonId"));

                    b.Property<int?>("DichVuId")
                        .HasColumnType("integer");

                    b.Property<double>("DonGia")
                        .HasColumnType("double precision");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TongTien")
                        .HasColumnType("double precision");

                    b.HasKey("ChiTietHoaDonId");

                    b.HasIndex("DichVuId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("chi_tiet_hoa_don");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.ChiTietThanhVienHopDong", b =>
                {
                    b.Property<int>("ChiTietThanhVienHopDongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChiTietThanhVienHopDongId"));

                    b.Property<int>("HopDongId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgayChuyenDi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayVao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiThueId")
                        .HasColumnType("integer");

                    b.HasKey("ChiTietThanhVienHopDongId");

                    b.HasIndex("HopDongId");

                    b.HasIndex("NguoiThueId");

                    b.ToTable("chi_tiet_thanh_vien_hop_dong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.DangKyDichVu", b =>
                {
                    b.Property<int>("DangKyDichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DangKyDichVuId"));

                    b.Property<int>("DichVuChiNhanhId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("DangKyDichVuId");

                    b.HasIndex("DichVuChiNhanhId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("dang_ky_dich_vu");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.DichVu", b =>
                {
                    b.Property<int>("DichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DichVuId"));

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LoaiDichVu")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DichVuId");

                    b.ToTable("dich_vu");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.DichVuDienNuocCuaPhong", b =>
                {
                    b.Property<int>("DichVuDienNuocCuaPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DichVuDienNuocCuaPhongId"));

                    b.Property<double>("ChiSoDienCu")
                        .HasColumnType("double precision");

                    b.Property<double>("ChiSoDienMoi")
                        .HasColumnType("double precision");

                    b.Property<double>("ChiSoNuocCu")
                        .HasColumnType("double precision");

                    b.Property<double>("ChiSoNuocMoi")
                        .HasColumnType("double precision");

                    b.Property<double>("DonGiaDien")
                        .HasColumnType("double precision");

                    b.Property<double>("DonGiaNuoc")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.HasKey("DichVuDienNuocCuaPhongId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("dich_vu_dien_nuoc_cua_phong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.DieuKhoanMau", b =>
                {
                    b.Property<int>("DieuKhoanMauId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DieuKhoanMauId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("DieuKhoanMauId");

                    b.ToTable("dieu_khoan_mau");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HoaDonId"));

                    b.Property<int?>("DichVuDienNuocCuaPhongId")
                        .HasColumnType("integer");

                    b.Property<int>("HopDongId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<double>("TongTien")
                        .HasColumnType("double precision");

                    b.Property<int>("TrangThaiHoaDon")
                        .HasColumnType("integer");

                    b.HasKey("HoaDonId");

                    b.HasIndex("DichVuDienNuocCuaPhongId");

                    b.HasIndex("HopDongId", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("hoa_don");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.HopDong", b =>
                {
                    b.Property<int>("HopDongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HopDongId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaHopDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiThueId")
                        .HasColumnType("integer");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiDiemBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ThoiDiemKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TienCocPhong")
                        .HasColumnType("double precision");

                    b.Property<double>("TienThuePhong")
                        .HasColumnType("double precision");

                    b.Property<int>("TrangThaiHopDong")
                        .HasColumnType("integer");

                    b.HasKey("HopDongId");

                    b.HasIndex("NguoiThueId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("hop_dong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.HopDongDieuKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HopDongId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("HopDongId");

                    b.ToTable("hop_dong_dieu_khoan");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.LichSuThanhToan", b =>
                {
                    b.Property<int>("LichSuThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LichSuThanhToanId"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiXacNhanId")
                        .HasColumnType("integer");

                    b.Property<int>("PhuongThucThanhToan")
                        .HasColumnType("integer");

                    b.Property<double>("SoTienThanhToan")
                        .HasColumnType("double precision");

                    b.HasKey("LichSuThanhToanId");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("NguoiXacNhanId");

                    b.ToTable("lich_su_thanh_toan");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NguoiDungId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiThueId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NguoiDungId");

                    b.HasIndex("NguoiThueId")
                        .IsUnique();

                    b.ToTable("nguoi_dung");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.NguoiThue", b =>
                {
                    b.Property<int>("NguoiThueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NguoiThueId"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgayCapCCCD")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiCapCCCD")
                        .HasColumnType("text");

                    b.Property<string>("QueQuan")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NguoiThueId");

                    b.ToTable("nguoi_thue");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.PhongTro", b =>
                {
                    b.Property<int>("PhongTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhongTroId"));

                    b.Property<int>("ChiNhanhId")
                        .HasColumnType("integer");

                    b.Property<double>("DienTich")
                        .HasColumnType("double precision");

                    b.Property<double>("GiaThue")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("integer");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TangLau")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("PhongTroId");

                    b.HasIndex("ChiNhanhId");

                    b.ToTable("phong_tro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinhVuc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LinkDieuHuong")
                        .HasColumnType("text");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("thong_bao");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.YeuCauSuCo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ChiPhiSuaChua")
                        .HasColumnType("double precision");

                    b.Property<bool>("CongVaoHoaDon")
                        .HasColumnType("boolean");

                    b.Property<string>("GhiChuAdmin")
                        .HasColumnType("text");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LyDoTuChoi")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiThueId")
                        .HasColumnType("integer");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("integer");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NguoiThueId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("yeu_cau_su_co");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Areas.QuanLyNhaTro.Models.DichVuChiNhanh", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.ChiNhanh", "ChiNhanh")
                        .WithMany("DichVuChiNhanhs")
                        .HasForeignKey("ChiNhanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.DichVu", "DichVu")
                        .WithMany("DichVuChiNhanhs")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuId");

                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonDichVus")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.ChiTietThanhVienHopDong", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.HopDong", "HopDong")
                        .WithMany("ChiTietThanhVienHopDongs")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.NguoiThue", "NguoiThue")
                        .WithMany("ChiTietThanhVienHopDongs")
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("NguoiThue");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.DangKyDichVu", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Areas.QuanLyNhaTro.Models.DichVuChiNhanh", "DichVuChiNhanh")
                        .WithMany("DangKyDichVus")
                        .HasForeignKey("DichVuChiNhanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.PhongTro", "PhongTro")
                        .WithMany("DangKyDichVus")
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVuChiNhanh");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.DichVuDienNuocCuaPhong", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.PhongTro", "PhongTro")
                        .WithMany()
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.DichVuDienNuocCuaPhong", "DichVuDienNuocCuaPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("DichVuDienNuocCuaPhongId");

                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVuDienNuocCuaPhong");

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.HopDong", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.NguoiThue", "NguoiThue")
                        .WithMany("HopDongs")
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.PhongTro", "PhongTro")
                        .WithMany("HopDongs")
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiThue");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.HopDongDieuKhoan", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.HopDong", "HopDong")
                        .WithMany("HopDongDieuKhoans")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.LichSuThanhToan", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.HoaDon", "HoaDon")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.NguoiDung", "NguoiXacNhan")
                        .WithMany()
                        .HasForeignKey("NguoiXacNhanId");

                    b.Navigation("HoaDon");

                    b.Navigation("NguoiXacNhan");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.NguoiThue", "NguoiThue")
                        .WithOne("NguoiDung")
                        .HasForeignKey("QuanLyChoThuePhongTroWeb.Models.NguoiDung", "NguoiThueId");

                    b.Navigation("NguoiThue");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.PhongTro", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.ChiNhanh", "ChiNhanh")
                        .WithMany("PhongTros")
                        .HasForeignKey("ChiNhanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.YeuCauSuCo", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Models.PhongTro", "PhongTro")
                        .WithMany()
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiThue");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Areas.QuanLyNhaTro.Models.DichVuChiNhanh", b =>
                {
                    b.Navigation("DangKyDichVus");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.ChiNhanh", b =>
                {
                    b.Navigation("DichVuChiNhanhs");

                    b.Navigation("PhongTros");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.DichVu", b =>
                {
                    b.Navigation("DichVuChiNhanhs");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.DichVuDienNuocCuaPhong", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDonDichVus");

                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.HopDong", b =>
                {
                    b.Navigation("ChiTietThanhVienHopDongs");

                    b.Navigation("HoaDons");

                    b.Navigation("HopDongDieuKhoans");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.NguoiThue", b =>
                {
                    b.Navigation("ChiTietThanhVienHopDongs");

                    b.Navigation("HopDongs");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Models.PhongTro", b =>
                {
                    b.Navigation("DangKyDichVus");

                    b.Navigation("HopDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
