// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyChoThuePhongTroWeb.Infrastructure.Persistence;

#nullable disable

namespace QuanLyChoThuePhongTroWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921155855_AddBillingOcrAndInvoicePayments")]
    partial class AddBillingOcrAndInvoicePayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.AnhChiSoDongHo", b =>
                {
                    b.Property<int>("AnhChiSoDongHoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnhChiSoDongHoId"));

                    b.Property<int>("DichVuDienNuocCuaPhongId")
                        .HasColumnType("integer");

                    b.Property<double?>("DoTinCay")
                        .HasColumnType("double precision");

                    b.Property<bool>("DuocChonLamChiSoChinhThuc")
                        .HasColumnType("boolean");

                    b.Property<string>("GhiChuXacNhan")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("GiaTriAIGoiY")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("GiaTriXacNhan")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LoaiDongHo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiGuiId")
                        .HasColumnType("integer");

                    b.Property<int?>("NguoiXacNhanId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ThongBaoLoi")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TrangThaiXuLy")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("AnhChiSoDongHoId");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiXacNhanId");

                    b.HasIndex("DichVuDienNuocCuaPhongId", "LoaiDongHo")
                        .IsUnique()
                        .HasFilter("\"DuocChonLamChiSoChinhThuc\" = true AND \"IsDeleted\" = false");

                    b.ToTable("anh_chi_so_dong_ho", t =>
                        {
                            t.HasCheckConstraint("CK_AnhChiSoDongHo_ChiSoChinhThuc", "NOT \"DuocChonLamChiSoChinhThuc\" OR (\"GiaTriXacNhan\" IS NOT NULL AND \"NguoiXacNhanId\" IS NOT NULL AND \"NgayXacNhan\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_AnhChiSoDongHo_DoTinCay", "\"DoTinCay\" IS NULL OR (\"DoTinCay\" >= 0 AND \"DoTinCay\" <= 1)");

                            t.HasCheckConstraint("CK_AnhChiSoDongHo_GiaTri", "(\"GiaTriAIGoiY\" IS NULL OR \"GiaTriAIGoiY\" >= 0) AND (\"GiaTriXacNhan\" IS NULL OR \"GiaTriXacNhan\" >= 0)");
                        });
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.ChiNhanh", b =>
                {
                    b.Property<int>("ChiNhanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChiNhanhId"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaChiNhanh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChiNhanhId");

                    b.HasIndex("MaChiNhanh")
                        .IsUnique();

                    b.ToTable("chi_nhanh");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ChiTietHoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChiTietHoaDonId"));

                    b.Property<int?>("DichVuId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ChiTietHoaDonId");

                    b.HasIndex("DichVuId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("chi_tiet_hoa_don");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.ChiTietThanhVienHopDong", b =>
                {
                    b.Property<int>("ChiTietThanhVienHopDongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChiTietThanhVienHopDongId"));

                    b.Property<int>("HopDongId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgayChuyenDi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayVao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiThueId")
                        .HasColumnType("integer");

                    b.HasKey("ChiTietThanhVienHopDongId");

                    b.HasIndex("HopDongId");

                    b.HasIndex("NguoiThueId");

                    b.ToTable("chi_tiet_thanh_vien_hop_dong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DangKyDichVu", b =>
                {
                    b.Property<int>("DangKyDichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DangKyDichVuId"));

                    b.Property<int>("DichVuChiNhanhId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("DangKyDichVuId");

                    b.HasIndex("DichVuChiNhanhId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("dang_ky_dich_vu");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVu", b =>
                {
                    b.Property<int>("DichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DichVuId"));

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LoaiDichVu")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DichVuId");

                    b.ToTable("dich_vu");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuChiNhanh", b =>
                {
                    b.Property<int>("DichVuChiNhanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DichVuChiNhanhId"));

                    b.Property<int>("ChiNhanhId")
                        .HasColumnType("integer");

                    b.Property<int>("DichVuId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GiaDichVu")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DichVuChiNhanhId");

                    b.HasIndex("DichVuId");

                    b.HasIndex("ChiNhanhId", "DichVuId")
                        .IsUnique();

                    b.ToTable("dich_vu_chi_nhanh");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuDienNuocCuaPhong", b =>
                {
                    b.Property<int>("DichVuDienNuocCuaPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DichVuDienNuocCuaPhongId"));

                    b.Property<decimal>("ChiSoDienCu")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ChiSoDienMoi")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ChiSoNuocCu")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ChiSoNuocMoi")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("DonGiaDien")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DonGiaNuoc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("GhiChuDuyet")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("integer");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("integer");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiGhiNhan")
                        .HasColumnType("integer");

                    b.HasKey("DichVuDienNuocCuaPhongId");

                    b.HasIndex("PhongTroId", "Thang", "Nam")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("dich_vu_dien_nuoc_cua_phong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DieuKhoanMau", b =>
                {
                    b.Property<int>("DieuKhoanMauId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DieuKhoanMauId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("DieuKhoanMauId");

                    b.ToTable("dieu_khoan_mau");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HoaDonId"));

                    b.Property<bool>("ChoPhepThanhToanMotPhan")
                        .HasColumnType("boolean");

                    b.Property<int?>("DichVuDienNuocCuaPhongId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HopDongId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayChot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiChotId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SoTienThanhToanToiThieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TrangThaiHoaDon")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiPhatHanh")
                        .HasColumnType("integer");

                    b.HasKey("HoaDonId");

                    b.HasIndex("DichVuDienNuocCuaPhongId");

                    b.HasIndex("HopDongId", "Thang", "Nam")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("hoa_don");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.HopDong", b =>
                {
                    b.Property<int>("HopDongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HopDongId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaHopDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiThueId")
                        .HasColumnType("integer");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiDiemBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ThoiDiemKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TienCocPhong")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TienThuePhong")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TrangThaiHopDong")
                        .HasColumnType("integer");

                    b.HasKey("HopDongId");

                    b.HasIndex("NguoiThueId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("hop_dong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.HopDongDieuKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HopDongId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("HopDongId");

                    b.ToTable("hop_dong_dieu_khoan");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.LichSuThanhToan", b =>
                {
                    b.Property<int>("LichSuThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LichSuThanhToanId"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MinhChungThanhToanHoaDonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiXacNhanId")
                        .HasColumnType("integer");

                    b.Property<int>("PhuongThucThanhToan")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("LichSuThanhToanId");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("MaGiaoDich")
                        .IsUnique()
                        .HasFilter("\"MaGiaoDich\" IS NOT NULL AND \"MaGiaoDich\" <> '' AND \"IsDeleted\" = false");

                    b.HasIndex("MinhChungThanhToanHoaDonId")
                        .IsUnique()
                        .HasFilter("\"MinhChungThanhToanHoaDonId\" IS NOT NULL");

                    b.HasIndex("NguoiXacNhanId");

                    b.ToTable("lich_su_thanh_toan");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.LichSuTrangThaiHoaDon", b =>
                {
                    b.Property<int>("LichSuTrangThaiHoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LichSuTrangThaiHoaDonId"));

                    b.Property<int>("HoaDonId")
                        .HasColumnType("integer");

                    b.Property<string>("LyDo")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiThucHienId")
                        .HasColumnType("integer");

                    b.Property<int?>("TrangThaiPhatHanhCu")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiPhatHanhMoi")
                        .HasColumnType("integer");

                    b.Property<int?>("TrangThaiThanhToanCu")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiThanhToanMoi")
                        .HasColumnType("integer");

                    b.HasKey("LichSuTrangThaiHoaDonId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("lich_su_trang_thai_hoa_don");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.LichSuTrangThaiYeuCauThanhToanHoaDon", b =>
                {
                    b.Property<int>("LichSuTrangThaiYeuCauThanhToanHoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LichSuTrangThaiYeuCauThanhToanHoaDonId"));

                    b.Property<string>("LyDo")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiThucHienId")
                        .HasColumnType("integer");

                    b.Property<int?>("TrangThaiCu")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiMoi")
                        .HasColumnType("integer");

                    b.Property<int>("YeuCauThanhToanHoaDonId")
                        .HasColumnType("integer");

                    b.HasKey("LichSuTrangThaiYeuCauThanhToanHoaDonId");

                    b.HasIndex("YeuCauThanhToanHoaDonId");

                    b.ToTable("lich_su_trang_thai_yeu_cau_thanh_toan_hoa_don");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.MinhChungThanhToanHoaDon", b =>
                {
                    b.Property<int>("MinhChungThanhToanHoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MinhChungThanhToanHoaDonId"));

                    b.Property<string>("HinhAnhUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LyDoTuChoi")
                        .HasColumnType("text");

                    b.Property<string>("MaGiaoDichNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NgayChuyenKhaiBao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayDoiChieu")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiDoiChieuId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("SoTienKhaiBao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TrangThaiDoiChieu")
                        .HasColumnType("integer");

                    b.Property<int>("YeuCauThanhToanHoaDonId")
                        .HasColumnType("integer");

                    b.HasKey("MinhChungThanhToanHoaDonId");

                    b.HasIndex("YeuCauThanhToanHoaDonId");

                    b.ToTable("minh_chung_thanh_toan_hoa_don");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NguoiDungId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiThueId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NguoiDungId");

                    b.HasIndex("NguoiThueId")
                        .IsUnique();

                    b.ToTable("nguoi_dung");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiThue", b =>
                {
                    b.Property<int>("NguoiThueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NguoiThueId"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgayCapCCCD")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiCapCCCD")
                        .HasColumnType("text");

                    b.Property<string>("QueQuan")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NguoiThueId");

                    b.ToTable("nguoi_thue");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.PhongTro", b =>
                {
                    b.Property<int>("PhongTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhongTroId"));

                    b.Property<int>("ChiNhanhId")
                        .HasColumnType("integer");

                    b.Property<double>("DienTich")
                        .HasColumnType("double precision");

                    b.Property<decimal>("GiaThue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("integer");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TangLau")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("PhongTroId");

                    b.HasIndex("ChiNhanhId");

                    b.ToTable("phong_tro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinhVuc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LinkDieuHuong")
                        .HasColumnType("text");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("thong_bao");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.YeuCauSuCo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChiPhiSuaChua")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("CongVaoHoaDon")
                        .HasColumnType("boolean");

                    b.Property<string>("GhiChuAdmin")
                        .HasColumnType("text");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LyDoTuChoi")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiThueId")
                        .HasColumnType("integer");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("integer");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NguoiThueId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("yeu_cau_su_co");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.YeuCauThanhToanHoaDon", b =>
                {
                    b.Property<int>("YeuCauThanhToanHoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("YeuCauThanhToanHoaDonId"));

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaYeuCau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDungChuyenKhoan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("YeuCauThanhToanHoaDonId");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("MaYeuCau")
                        .IsUnique();

                    b.ToTable("yeu_cau_thanh_toan_hoa_don");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.AnhChiSoDongHo", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuDienNuocCuaPhong", "DichVuDienNuocCuaPhong")
                        .WithMany("AnhChiSoDongHos")
                        .HasForeignKey("DichVuDienNuocCuaPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiDung", "NguoiXacNhan")
                        .WithMany()
                        .HasForeignKey("NguoiXacNhanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DichVuDienNuocCuaPhong");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiXacNhan");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuId");

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonDichVus")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.ChiTietThanhVienHopDong", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.HopDong", "HopDong")
                        .WithMany("ChiTietThanhVienHopDongs")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiThue", "NguoiThue")
                        .WithMany("ChiTietThanhVienHopDongs")
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("NguoiThue");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DangKyDichVu", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuChiNhanh", "DichVuChiNhanh")
                        .WithMany("DangKyDichVus")
                        .HasForeignKey("DichVuChiNhanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.PhongTro", "PhongTro")
                        .WithMany("DangKyDichVus")
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVuChiNhanh");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuChiNhanh", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.ChiNhanh", "ChiNhanh")
                        .WithMany("DichVuChiNhanhs")
                        .HasForeignKey("ChiNhanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVu", "DichVu")
                        .WithMany("DichVuChiNhanhs")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuDienNuocCuaPhong", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.PhongTro", "PhongTro")
                        .WithMany()
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.HoaDon", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuDienNuocCuaPhong", "DichVuDienNuocCuaPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("DichVuDienNuocCuaPhongId");

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVuDienNuocCuaPhong");

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.HopDong", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiThue", "NguoiThue")
                        .WithMany("HopDongs")
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.PhongTro", "PhongTro")
                        .WithMany("HopDongs")
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiThue");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.HopDongDieuKhoan", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.HopDong", "HopDong")
                        .WithMany("HopDongDieuKhoans")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.LichSuThanhToan", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.MinhChungThanhToanHoaDon", "MinhChungThanhToanHoaDon")
                        .WithOne("LichSuThanhToan")
                        .HasForeignKey("QuanLyChoThuePhongTroWeb.Domain.Entities.LichSuThanhToan", "MinhChungThanhToanHoaDonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiDung", "NguoiXacNhan")
                        .WithMany()
                        .HasForeignKey("NguoiXacNhanId");

                    b.Navigation("HoaDon");

                    b.Navigation("MinhChungThanhToanHoaDon");

                    b.Navigation("NguoiXacNhan");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.LichSuTrangThaiHoaDon", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("LichSuTrangThaiHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.LichSuTrangThaiYeuCauThanhToanHoaDon", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.YeuCauThanhToanHoaDon", "YeuCauThanhToanHoaDon")
                        .WithMany("LichSuTrangThaiYeuCauThanhToanHoaDons")
                        .HasForeignKey("YeuCauThanhToanHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauThanhToanHoaDon");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.MinhChungThanhToanHoaDon", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.YeuCauThanhToanHoaDon", "YeuCauThanhToanHoaDon")
                        .WithMany("MinhChungThanhToanHoaDons")
                        .HasForeignKey("YeuCauThanhToanHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauThanhToanHoaDon");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiThue", "NguoiThue")
                        .WithOne("NguoiDung")
                        .HasForeignKey("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiDung", "NguoiThueId");

                    b.Navigation("NguoiThue");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.PhongTro", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.ChiNhanh", "ChiNhanh")
                        .WithMany("PhongTros")
                        .HasForeignKey("ChiNhanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.YeuCauSuCo", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiThue", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.PhongTro", "PhongTro")
                        .WithMany()
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiThue");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.YeuCauThanhToanHoaDon", b =>
                {
                    b.HasOne("QuanLyChoThuePhongTroWeb.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("YeuCauThanhToanHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.ChiNhanh", b =>
                {
                    b.Navigation("DichVuChiNhanhs");

                    b.Navigation("PhongTros");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVu", b =>
                {
                    b.Navigation("DichVuChiNhanhs");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuChiNhanh", b =>
                {
                    b.Navigation("DangKyDichVus");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.DichVuDienNuocCuaPhong", b =>
                {
                    b.Navigation("AnhChiSoDongHos");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDonDichVus");

                    b.Navigation("LichSuThanhToans");

                    b.Navigation("LichSuTrangThaiHoaDons");

                    b.Navigation("YeuCauThanhToanHoaDons");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.HopDong", b =>
                {
                    b.Navigation("ChiTietThanhVienHopDongs");

                    b.Navigation("HoaDons");

                    b.Navigation("HopDongDieuKhoans");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.MinhChungThanhToanHoaDon", b =>
                {
                    b.Navigation("LichSuThanhToan");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.NguoiThue", b =>
                {
                    b.Navigation("ChiTietThanhVienHopDongs");

                    b.Navigation("HopDongs");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.PhongTro", b =>
                {
                    b.Navigation("DangKyDichVus");

                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("QuanLyChoThuePhongTroWeb.Domain.Entities.YeuCauThanhToanHoaDon", b =>
                {
                    b.Navigation("LichSuTrangThaiYeuCauThanhToanHoaDons");

                    b.Navigation("MinhChungThanhToanHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
